# Generated by Django 6.0.1 on 2026-02-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_customuser_role_remove_profile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='DoB',
        ),
    ]
