# Generated by Django 6.0.1 on 2026-02-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DoB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
