# Generated by Django 6.0.1 on 2026-02-04 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ManyToManyField(blank=True, related_name='department', to='mainapp.servingteam')),
                ('dg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dg', to='mainapp.discipleshipgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
