# Generated by Django 6.0.1 on 2026-02-18 07:56

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_ministrydata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscipleshipGroup',
            new_name='FellowshipGroup',
        ),
        migrations.RemoveField(
            model_name='ministrydata',
            name='department',
        ),
        migrations.RemoveField(
            model_name='ministrydata',
            name='dg',
        ),
        migrations.RemoveField(
            model_name='ministrydata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ropesclass',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='ropesclass',
            name='members',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_duration', models.DurationField(help_text='Expected duration of the course in weeks')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ropes_class_leader', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='ropes_class', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='ServingTeam',
            new_name='Department',
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('crew', models.ManyToManyField(blank=True, related_name='services_crew', to='mainapp.department')),
                ('members', models.ManyToManyField(related_name='services', to=settings.AUTH_USER_MODEL)),
                ('pastor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_pastor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('assigned_department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='mainapp.department')),
                ('assigned_service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='mainapp.services')),
            ],
        ),
        migrations.DeleteModel(
            name='AgeGroup',
        ),
        migrations.DeleteModel(
            name='MinistryData',
        ),
        migrations.DeleteModel(
            name='RopesClass',
        ),
    ]
